services:
  db:
    image: postgres:15-alpine
    container_name: clips-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: clip
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: clips_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sb"]
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local