spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clips_db}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:clip}
    password: ${SPRING_DATASOURCE_PASSWORD:1}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  

api:
  security:
    token:  
      secret: ${JWT_SECRET:my-secret-key}
  twitch:
    url-auth: ${TWITCH_URL_AUTH:https://id.twitch.tv/oauth2/token}
    url-clips: ${TWITCH_URL_CLIPS:https://api.twitch.tv/helix/clips}
    broadcaster-id: ${TWITCH_BROADCASTER_ID:424213743}
    client-id: ${TWITCH_CLIENT_ID:nwc5hmli8ke9ns1sely38ohj5pp0hb}
    secret-id: ${TWITCH_SECRET_ID:i87emc9cnlnfow2wvjfgy2h1j5schx}
    grant-type: ${TWITCH_GRANT_TYPE:client_credentials}
  tiktok:
    url-auth: ${TIKTOK_URL_AUTH:https://open.tiktokapis.com/v2/oauth/token/}
    url-upload: ${TIKTOK_URL_UPLOAD:https://open.tiktok.com/platform/api/upload}
    client-id: ${TIKTOK_CLIENT_ID:awnthbkj14lpl7uq}
    secret-id: ${TIKTOK_SECRET_ID:xbwEiXwyMceb2ThciHWRmbuphABfnY7P}
    grant-type: ${TIKTOK_GRANT_TYPE:client_credentials}


logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
